services:
  backend:
    container_name: try-cb-api-mm
    platform: linux/amd64 # needed until libcouchbase releases arm64 images
    build: .
    ports:
      - 8080:8080
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD

  frontend:
    container_name: try-cb-fe-mm
    build: "https://github.com/couchbaselabs/try-cb-frontend-v2.git#7.0"
    ports:
      - 8081:8081

  db:
    container_name: couchbase-sandbox-7.0.0-mm
    image: couchbase/server-sandbox:7.0.0
    ports:
      - "8091-8095:8091-8095"
      - "9102:9102"
      - "11210:11210"
    expose: # expose ports 8091 & 8094 to other containers (mainly for backend)
      - "8091"
      - "8092"
      - "8093"
      - "8094"
      - "8095"
      - "9102"
      - "11210"
